#! /bin/zsh

bspc config border_width        	0
bspc config window_gap				12

bspc config split_ratio         	0.30
bspc config focus_follows_pointer 	false
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config focus_by_distance   	true

bspc monitor -d TERMINAL CODE WEB FILES TORRENTS MEDIA

bspc rule -a subl3 						desktop=^2 follow=no
bspc rule -a Google-chrome-stable		desktop=^3
bspc rule -a thunar 					floating=on
bspc rule -a file-roller 				floating=on

panel &
compton -cCzGf --backend xrender &

urxvt &
subl3 &
setxkbmap -model pc104 -layout us,ru -option grp:toggle
wmname LG3D