#! /bin/zsh

bspc config border_width        	0
bspc config window_gap				12

bspc config split_ratio         	0.40
bspc config focus_follows_pointer 	false
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config focus_by_distance   	true

# tabs' icons:	terminal		 sublime		  chrome		   pavucontrol+ts3	steam			 file-manager	   torrents			media
bspc monitor -d $(echo '\uf120') $(echo '\uf121') $(echo '\uf268') $(echo '\uf028') $(echo '\uf1b6') $(echo '\uf07c')  $(echo '\uf019') $(echo '\uf001')

bspc rule -a subl3 						desktop=^2
bspc rule -a Google-chrome-stable 		desktop=^3
bspc rule -a thunar 					floating=on
bspc rule -a nautilus 					floating=on
bspc rule -a file-roller 				floating=on

panel &
compton -c &
urxvt &
subl3 &
setxkbmap -model pc104 -layout us,ru -option grp:toggle
